#%RAML 1.0 DocumentationItem
title: Salesforce account management Home
content: |
  ** Salesforce account management API** enables developers to build applications that make use of the Salesforce Cloud Connector to manage Salesforce Account through HTTP methods implemented in the API.

